version: '3.8'

services:
  db:
    image: postgres:14.6
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'dkconsult'
      POSTGRES_USER: 'denis'
      POSTGRES_PASSWORD: 'dk1011'

  backend:
    build: ./backend
    privileged: true
    restart: always
    expose:
      - 8080
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: bash -c " python manage.py makemigrations && python manage.py migrate && gunicorn backend.wsgi -b 0.0.0.0:8080 "

  nginx:
    build: ./nginx
    privileged: true
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./dk-consulting
    privileged: true
    restart: always
    ports:
      - 80:80
    depends_on:
      - nginx
