# Generated by Django 3.2.15 on 2022-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='channel_type',
            field=models.CharField(choices=[('SCL', 'СОЦИАЛЬНЫЕ СЕТИ'), ('WEB', 'ПОИСК В ИНТЕРНЕТЕ'), ('REC', 'РЕКОМЕНДАЦИИ'), ('OTHER', 'ДРУГОЙ ИСТОЧНИК')], max_length=64, verbose_name='Источник информации'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='request_type',
            field=models.CharField(choices=[('AUDIT', 'АУДИТ'), ('IND_CONSLT', 'ПРОМЫШЛЕННЫЙ КОНСАЛТИНГ'), ('ORG', 'ОРГАНИЗАЦИЯ ПРОИЗВОДСТВА'), ('LRN', 'ОБУЧЕНИЕ')], max_length=64, verbose_name='Тип запроса'),
        ),
    ]
