# Generated by Django 3.2.15 on 2022-11-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Имя файла')),
                ('description', models.CharField(max_length=128, verbose_name='Описание файла')),
                ('for_clients', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Полезный материал',
                'verbose_name_plural': 'Полезные материалы',
            },
        ),
    ]
