# Generated by Django 3.2.15 on 2022-11-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file_name',
            field=models.FileField(default=1, upload_to='uploads/', verbose_name='Файл pdf'),
            preserve_default=False,
        ),
    ]
